version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyWeirdPass! # Cambia esta clave a una segura
    volumes:
      - /home/oxigenocc/data-db/:/var/lib/postgresql/data # Cambia oxigenocc por el nombre del usuario de tu host
  db2:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyWeirdPass!
    volumes:
      - /home/oxigenocc/data-db/:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    command: gunicorn --bind 0.0.0.0:5000 mysite.wsgi:application
    environment:
      - SECRET_KEY=<django_secret_key> # Cambia esto por una generada aquí https://miniwebtool.com/django-secret-key-generator/
      - API_KEY=<google_maps_api_key> # Cambia esto por tu API key de google maps
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=MyWeirdPass!
      - DB_HOST=db2
      - DB_PORT=5432
      - ALLOWED_HOSTS=myhost.com,www.myhost.com # Cambia esto por el dominio que vas a usar en tu host
      - DEBUG=True
      - STATIC_ROOT=/home/oxigenocc/static # Cambia esto a la ruta de tu directorio de static
    ports:
      - "5000:5000"
    depends_on:
      - db
      - db2
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8000:8000"
