site_name: Oxigeno.cc
site_description: Oxigeno.cc API Doc
repo_url: https://github.com/oxigenocc/oxigeno.cc
site_dir: https://oxigeno.cc/
copyright: Copyright &copy; 2020, <a href="https://github.com/oxigenocc/oxigeno.cc">Oxigeno.cc</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API: 'index.md'

theme: readthedocs